INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (1,"Air conditioner");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (2,"A fully functional kitchen");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (3,"Coffee maker");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (4,"Free parking");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (5,"WiFi");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (6,"Set of wine glasses");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (7,"Pet-friendly environment");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (8,"Pool");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (9,"Heating system");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (10,"Jacuzzi");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (11,"TV");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (12,"Washing machine");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (13,"Kettle");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (14,"Rice cooker");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (15,"Processors");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (16,"Blenders");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (17,"Bottle openers");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (18,"Corkscrews");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (19,"Juicers");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (20,"Roasting pan");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (21,"Thermometer");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (22,"Colander");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (23,"Turkey baster");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (24,"Vegetable peeler");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (25,"Brining bag");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (26,"Fishing pole");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (27,"Body lotion");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (28,"Hair conditioner");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (29,"Mouthwash");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (30,"Makeup remover wipes");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (31,"Disposable razors");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (32,"Shower caps");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (33,"Face mask samples");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (34,"Shaving cream");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (35,"Airport pick up/drop off");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (36,"City transfers");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (37,"Chauffeur service");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (38,"Sightseeing tours");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (39,"Complimentary Breakfast");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (40,"Stocked Fridge");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (41,"Food Storage Containers");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (42,"Kid-Friendly Equipment");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (43,"Pet-Friendly Amenities");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (44,"Hairdryer");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (45,"Beach Supplies");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (46,"Bicycles");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (47,"Private Pool");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (48,"Barbecue");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (49,"Parking Space");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (50,"Metered EV Charger");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (51,"Fast WiFi");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (52,"Cable Tv");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (53,"Surround Sound System");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (54,"Game Console");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (55,"Family Friendly Games");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (56,"Mountain view");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (57,"Private deck");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (58,"Fishing Pond");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (59,"Hiking Trails");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (60,"Hot Tub");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (61,"Fireplace");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (62,"Multi-surface cleaner");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (63,"Toaster");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (64,"Microwave");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (65,"Dishwasher");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (66,"Oven");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (67,"Outdoor furniture");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (68,"Security camera");
INSERT INTO Amenity (﻿AmenityID,AmenityName) VALUES (69,"Fire Extinguisher");